;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/GameTags/PlayerGameTags.PlayerGameTags
+GameplayTagTableList=/Game/GameTags/EnemyGameTags.EnemyGameTags
+GameplayTagTableList=/Game/GameTags/EnemyTraitTags.EnemyTraitTags
+GameplayTagTableList=/Game/GameTags/InteractionActorTag.InteractionActorTag
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Behavior.AI.Interact.Sit",DevComment="AI 与椅子互动时的坐下行为")
+GameplayTagList=(Tag="Behavior.AI.Interact.Sleep",DevComment="AI 与床互动时的睡觉行为")
+GameplayTagList=(Tag="Interaction.Action.OpenDoor",DevComment="AI 与门交互时使用的开门行为")
+GameplayTagList=(Tag="Interaction.Target.Bed",DevComment="AI 与床交互目标")
+GameplayTagList=(Tag="Interaction.Target.Chair",DevComment="AI 与椅子交互目标")
+GameplayTagList=(Tag="Interaction.Target.Door",DevComment="可被 AI 编辑模式识别的滑动门目标")
+GameplayTagList=(Tag="KeyCard.Security.Level1",DevComment="默认钥匙卡示例，门与钥匙卡可使用同一 Tag 匹配")
+GameplayTagList=(Tag="KeyCard.Security.Level2",DevComment="")

